//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace InventoryERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [Required]
        public System.Guid OrderId { get; set; }
        [Display(Name = "Order Number")]
        public string OrderNumber { get; set; }
        [Required]
        public decimal OrderTotal { get; set; }

        public string Status { get; set; } = "Active";
        public Nullable<System.Guid> LocationId { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
